---
title: "Triple-D data formatting"
output: html_document
---

# Stations
# General remarks
test_Lavaleye: The raw data included station info together with biological data. The "remove duplicates" function in Excel was used to only keep one entry per station.  

The RWS data do not have a cruise ID, so instead the cleaned csv files are named RWS_<zaaknr>. The "zaaknummer" is the number sequence at the start of the original data files as stored in DAS. For the RWS data 2018 and 2019, stations with a failed dredge were removed, to prevent double stationIDs.

## StationID
For the NICO10 cruise (64PE438) the station numbers are the same as in CASINO.
test_Lavaleye: StCode is same as StationID.
RWS2018: Station ID is RWS31135633#<station nr reported before _FrieseFront in the column Loc_name> using the Excelcode: ="RWS31135633#"&LEFT(A2,FIND("_",A2)-1).
RWS2019: Station ID is RWS31144108#<station nr reported before _ in the column Loc_name> using the Excelcode: ="RWS31144108#"&LEFT(A2,FIND("_",A2)-1).

## Date
For the NICO10 cruise (64PE438) the date for all samples is taken from the cruise report.
test_Lavaleye: Already reported in correct format.
RWS2018/2019: "DATE_SMP" is Date.

## Lat_start_DD and Lon_start_DD
For the NICO10 cruise (64PE438) these correspond to the position of the ship when the dredge touched bottom. Taken from CASINO extract in cruise report.
test_Lavaleye: Not available.
RWS2018/2019: "Position_x, begin"	"Position_y, begin" are Lon_start_DD and Lat_start_DD. The coordinate system was "EPSG4258".


## Lat_stop_DD and Lon_stop_DD
For the NICO10 cruise (64PE438) these correspond to the position of the ship when the dredge was heaved. Taken from CASINO extract in cruise report.
test_Lavaleye: Not available. 
RWS2018/2019: "Position_x, eind"	"Position_y, eind" are Lon_stop_DD and Lat_stop_DD. The coordinate system was "EPSG4258".

## Lat_DD_midpt and Lon_DD_midpt
The Lat(DD) and Lon(DD) for the NICO10 cruise (64PE438) are calculated from the position of the ship, the position of the antenna on the ship, the estimated angle of the veered cable, and the length of the veered cable as follows:  
**CODE BY ROB**
Taken from the excel file provided by Rob Witbaard.
test_Lavaleye: Reported, but unclear how these were obtained: ship or dredge positions? Midpoint of track?
RWS2018/2019: "COORD_Y" is Lat_DD_midpt and "COORD_X" is Lon_DD_midpt. The coordinate system was "EPSG4258".

## Track_length_m_Odo
For the NICO10 cruise (64PE438) these correspond to the odometer. Taken from CASINO extract in cruise report.
test_Lavaleye: Track length is Track_dist(m). Are these all measured with odometers, or also other methods to derive track distance?
RWS2018/2019: The variable "AMT_MEAS" is the area that was measured in m2. Because the blade width is 20 cm, the track length can be deduced from area and blade width (2018: all track lengths are 100m, 2019: track lengths are all near 100m).

## Blade_depth_cm
During the NICO10 cruise (64PE438) a blade of 20x20 cm was used.
test_Laveleye: depth of blade is not recorded. For now assumed 20 cm, is this correct for all data? In prototype paper other possible depths were also recorded.
RWS2018: "Schaafdiepte (cm)" used for blade depth.

## Blade_width_cm
During the NICO10 cruise (64PE438) a blade of 20x20 cm was used.
test_Laveleye: width is blade width in meters, so multiplied x100 to obtain value in cm. 
RWS2018/2019: Blade width assumed to be 20 cm?

## Vessel
NICO10 cruise (64PE438): RV Pelagia
test_Laveleye: Not available.
RWS2018/2019: NA.

## CruiseID
NICO10 cruise (64PE438)
test_Laveleye: CruiseID is Cruise in raw data.
RWS2018/2019: NA.

## Cruise_name
NICO10 cruise (64PE438)
test_Laveleye: Cruise_name is CruiseName in raw data.
RWS2018/2019: NA.

## Station_name
NICO10 cruise (64PE438): station names can be used to relate to other samples taken at these locations (boxcores, nutrient samples, etc.) as reported in the cruise report.
test_Laveleye: can we use Station in raw data for this field?
RWS2018/2019: "Loc_name" used.

## Region
NICO10 cruise (64PE438): not included
test_Laveleye: Available in raw data.
RWS2018: All data from Frysian Front, so set to FF.
RWS2019: Regions were manually added based on the station name. Bruinebank = BB, Doggersbank = DB, FrieseFront = FF, Oestergronden = OG, Oestergronden_ov = OG, Offshore = NA.

## Time_start and Time_stop
NICO10 cruise (64PE438): Time when dredge touched bottom, taken from CASINO extract in cruise report is start. Time when dredge was heaved, taken from CASINO extract in cruise report is end.
test_Laveleye: Not available.
RWS2018: "TIME_OBS" used for Time_start. Time_stop set to NA.
RWS2019: "TIME_OBS" used for Time_start. Time_stop set to NA. Original times were reported as "HHMM", so they were converted to the correct format "HH:MM:SS" by using the Excel code <=LEFT(A1,2)&":"&RIGHT(A1,2)&":00">.

## Tow_speed_knots
NICO10 cruise (64PE438): not included.
test_Laveleye: Not available.
RWS2018/2019: NA.

## Water_depth_start_m
NICO10 cruise (64PE438): not included.
test_Laveleye: Not available.
RWS2018/2019: NA.

## Water_depth_stop_m
NICO10 cruise (64PE438): not included.
test_Laveleye: Not available.
RWS2018/2019: Na.

## Water_depth_m_cruise
NICO10 cruise (64PE438): how is this measured? Taken from CASINO extract in cruise report.
test_Laveleye: Available, unclear how these values are obtained.
RWS2018: The variable "MONSDTE" is used as depth in meters, as the column "UNT_MONSDTE" specifies "m" for all entries.
RWS2019: The variable "MONSDTE (m t.o.v. NAP)" is used. The original negative values are converted to be positive. The unit of water depth is reported relative to NAP (Normalized Amsterdam Reference).

## Pre-run_setting
NICO10 cruise (64PE438): ? Taken from CASINO extract in cruise report.
test_Laveleye: Not available.
RWS2018/2019: NA.

## Cable_length_m
NICO10 cruise (64PE438): ? Taken from CASINO extract in cruise report.
test_Laveleye: Not available.
RWS2018/2019: NA.

## SB_count
NICO10 cruise (64PE438): ? Taken from CASINO extract in cruise report.
test_Laveleye: Not available.
RWS2018/2019: NA.

## BB_count
NICO10 cruise (64PE438): ? Taken from CASINO extract in cruise report.
test_Laveleye: Not available.
RWS2018/2019: NA.

## isBladeDeployed
NICO10 cruise (64PE438): Taken from CASINO extract in cruise report. Column Plate was used, so that OK was isBladeDeployed = 1, No was isBladeDeployed = 0, and NA was kept NA.
test_Laveleye: Not available.
RWS2018/2019: NA.


## Quality
NICO10 cruise (64PE438): included, based on the performance parameters of the dredge track. Taken from CASINO extract in cruise report.
test_Laveleye: Not available.
RWS2018/2019: NA.

## Comment
RWS2019: "smp_memo" is used.



# Species
## General remarks

## StationID
For the NICO10 cruise (64PE438) the station numbers are the same as in CASINO.  
test_Lavaleye: StCode is same as StationID.  
RWS2018: Station ID is RWS31135633#<station nr reported before _FrieseFront in the column Loc_name> using the Excelcode: ="RWS31135633#"&LEFT(A2,FIND("_",A2)-1).
RWS2019: Station ID is RWS31144108#<station nr reported before _ column Loc_name> using the Excelcode: ="RWS31144108#"&LEFT(A2,FIND("_",A2)-1).  

## Fraction
NICO10 cruise (64PE438): Fractions reported as 1/1, 1/2, 1/4 and 1/8 were reported as 1.0, 0.5, 0.25, and 0.125. There were some double entries (combination species - station with differing fractions):  

Arctica islandica 64PE438#122    0.5 -> fraction set to 1, the count was changed 1x2, and WetWeight was changed 1.5x2, isBulkWeight set to 1. Comment "Manually set fraction to 1 from 0.5."    
Arctica islandica 64PE438#122    1      

Porifera          64PE438#122    0.5 -> fraction set to 1, count changed 1x2, isBulkWeight set to 1. Comment "Manually set fraction to 1 from 0.5."                       
Porifera          64PE438#122    1               

Nucula spp        64PE438#214    1 -> In total 9 individuals of Nucula spp were found. Three were recorded so the fraction for all Nucula spp was set to 0.33, isBulkWeight of this individual set to 0.  
Nucula spp        64PE438#214    0.25           

Polychaeta spp    64PE438#215    1                     
Polychaeta spp    64PE438#215    0.125 -> In total 82 individuals were found, of which 12 were recorded. So the fraction for all Polychaeta spp was set to 12/82=0.146.   


test_Lavaleye: Taken from raw data.  

RWS2018: " FCT-A " is used as Fraction.
RWS2019: Fraction was calculated as 1/"FCT-A".

## isFractionAssumed
NICO10 cruise (64PE438): Fractions were specifically reported so isFractionAssumed = 0.  

test_Lavaleye: isFractionAssumed is based on the column AssumedFraction in raw data. In this case the column was empty, so all fractions were set to isFractionAssumed = 0.

RWS2018/2019: Specifically given in original data file, so set to 0.

## Species_reported
NICO10 cruise (64PE438): Species name taken for Species_reported.  

test_Lavaleye: Taken from raw data.

RWS2018/2019: "PAR_Name" is used.

## Count
NICO10 cruise (64PE438): reported in raw data. NA counts were set to -1.    

test_Lavaleye: "Number"" column is taken as Count.

RWS2018: "AMT_MEAS" is used. How was dealt with species with count 0? Set to -1?
RWS2019: "AMT_MEAS" was used. The entries in this column with value 0, also had the note ">" in column "IND_MEAS". Therefore, all n = 0 measurements were set to -1.

## Unit_Length
NICO10 cruise (64PE438): Maatvoering is taken for Unit_Length. 1/2 cm (with space) was converted to 1/2cm (without space).  

test_Lavaleye: 'unit length' taken for Unit_Length. 0.5cm was converted to 1/2cm. na was converted to NA.  

## Length
NICO10 cruise (64PE438): Size is taken for Length. Not clear what dimensions were measured as "size". Ask Rob.  

test_Lavaleye: reported in raw data.  

## Unit_Width
NICO10 cruise (64PE438): 'Maatvoering' is taken for Unit_Width if the comment denotes the measurement concerned width not length. Unit_Length is set to NA for these entries.    

test_Lavaleye: 'unit length' taken for Unit_Width if the notes in the original file mention the measured dimension is in fact width not length.  

## Width
NICO10 cruise (64PE438): Values reported in 'Size' with a comment that it concerned width of the individual were reported in Width, Length for these entries was set to NA.  

test_Lavaleye: The values reported in 'Width' are used, or the values in 'Length' if the notes/comments in the file mention that the value actually concerns a width not length.    

## WetWeight(g)
NICO10 cruise (64PE438): Reported in raw data. Entries of <0.5 were set to 0.  

test_Lavaleye: scale gWweight with shell is WetWeight(g). Not measured.

## isBulkWeight
NICO10 cruise (64PE438): If at one sampling station multiple entries of one species exists or if there is one entry with a count > 1, isBulkWeight is set to 1 for all entries (so also for the species with a WetWeight of NA). isBulkWeight was only set to 0 if there was only one individual of that species in the sample. Ask Rob about Arctica islandica.

test_Lavaleye: NA.  


## Threshold_Scale
NICO10 cruise (64PE438): All specimens were measured with the same scale with a threshold of 0.5 grams.

test_Lavaleye: NA.  


## isWithShell
NICO10 cruise (64PE438): Assumed all organisms are weighted as a whole, unless the comment indicates otherwise.

test_Lavaleye: NA (for now).  

## isPartialWW
NICO10 cruise (64PE438): Based on the comment isPartialWW was set to 1 if it was suspected the reported weight only concern part of the organism.  

test_Lavaleye: NA (for now).  

## ID_by
NICO10 cruise (64PE438): Not reported in raw data.
RWS2018/2019: "Controle" is used. Empty spaces filled with NA using Excel Find & Select > Go To Special > Select Blanks > OK > "NA" > ctrl+enter.

## isPreserved
NICO10 cruise (64PE438): Not reported in raw data.

test_Lavaleye: Preserved is isPreserved. NA (for now).  

## Comment
NICO10 cruise (64PE438): Used comments from raw data (in Dutch).
test_Lavaleye: Remark is used for Comment. Empty cells filled with NA.
RWS2018/2019: "RMK_MEAS" is used.
