---
title: "Method for processing Triple-D catch"
output: html_document
---

This vignette manual describes how specimens collected with the TripleD can be processed onboard so that the data can be readily added to the TripleD database. For every dredge, i.e. sampling station, with the TripleD:  

# Identification
1. Identify all collected specimens preferably to species level, and sort them accordingly. Report the species.  
2. For every species decide on the fraction of each species you want to process i.e. measure, weigh, etc. For example, if you have collected 20 specimens of *Asterias rubens* (seastars) you can decide to process 25% of that species, so you discard 75% (15 specimens) of *Asterias rubens* and process a representative 25% (5 specimens) of the species. Report the fraction.    

# Size measurements
3. Measure the length of each specimen in the appropriate units. It is also possible to measure the width of the specimen and/or an alternative body-part like a claw. What dimension of the organism's body is considered the standard length, standard width, or a standardized alternative dimension is reported below.  
4. Report the measured value in the relevent column Length, Width, or Alternative_dimension. Report the unit of the measurement in Unit_Length, Unit_Width, or Unit_Alternative. If an alternative dimension is measured, report the name of the dimension / body-part in the column Dimension_name.  

# Weighting
5. Note the threshold value of the scale that was used.  
6. Weigh each specimen to obtain a wet weight. Previously, a special weighting scale of Mark Fonds was used. If it is too much work to weigh individual specimens, multiple specimens - preferably the whole fraction or  specimens of the same size - can be grouped and weighted.  
6. Report the wet weight in grams for the (group of) specimen(s):  
- If the weight concerns multiple individuals, report isBulkWeight as 1 or TRUE.  
- If the weight is below the threshold value of the scale, report the weight as 0.  
- If the specimen was not complete, i.e. broken or consisted of a collection of body parts, report isPartialWW as 1 or TRUE to show the wet weight does not accurately represent a complete organism.   
- If a (group of) specimen(s) was measured without shell, report isWithShall as 0 or FALSE.  


# Conversion
Questions about the conversions:  
- How was it decided to convert 0.5 cm to mm or cm? Why was there decided to round 0.5cm up in conversion to mm? So, 2x0.5cm is not 10 mm but 15 mm. I understand for the measurements <0.5cm thus 0x0.5cm, but maybe not for the other measurements. Doesn't this lead to overestimation? The conversion to cm does not add this half a cm, and simply divides the value in half, so 5x0.5cm is 2.5 cm.
- For Cirolana borealis, how was the conversion factor to go from gram Dry weight to gram AFDW determined?  

